In [1]:
import pandas as pd
df = pd.read_excel("111597639_1572146776530.xls")

In [2]:
df

,HDFC BANK Ltd. Page No .: 1 Statement of accounts,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Account Branch :SALT LAKE SECTOR 1,NaN,NaN
4,MR SOMIL SHARMA,NaN,NaN,NaN,"Address :BB-22,",NaN,NaN
5,CO6NIHANT TECHNOLOGY SOLUTION CO P,NaN,NaN,NaN,SECTOR 1,NaN,NaN
6,BLDG CNADOOK TECHSPACE SEC TOWER B1,NaN,NaN,NaN,SALT LAKE CITY,NaN,NaN
7,2ND FL PLOT DH1 DH2 RAJARHAT NEWTOW,NaN,NaN,NaN,City :KOLKATA 700064,NaN,NaN
8,KOLKATA 700156,NaN,NaN,NaN,State :WEST BENGAL,NaN,NaN
9,WEST BENGAL INDIA,NaN,NaN,NaN,Phone no. :033-61606161,NaN,NaN
10,NaN,NaN,NaN,NaN,Email :SOMILSHARMA8@GMAIL.COM,NaN,NaN
11,JOINT HOLDERS :,NaN,NaN,NaN,OD Limit :0.00 Currency :INR,NaN,NaN
12,NaN,NaN,NaN,NaN,Cust ID :111597639,NaN,NaN
13,Nomination : Registered,NaN,NaN,NaN,Account No :50100217453044 OTHER,NaN,NaN
14,Statement From : 01/09/2019 To : 2...,NaN,NaN,NaN,A/C Open Date :28/11/2017,NaN,NaN
15,NaN,NaN,NaN,NaN,Account Status :Regular,NaN,NaN
16,NaN,NaN,NaN,NaN,RTGS/NEFT IFSC :HDFC0000018 MICR :700240004,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,**********************************************...,NaN,NaN,NaN,NaN,NaN,NaN
19,Date,Narration,Chq./Ref.No.,Value Dt,Withdrawal Amt.,Deposit Amt.,Closing Balance
20,********,**********************************,************,********,******************,******************,******************
21,02/09/19,UPI-AKASHI FILLING STATI-PAYTM-18113146@PAYTM-...,0000924521186955,02/09/19,1210,NaN,172.9
22,02/09/19,UPI-BHARATPE MERCHANT-BHARATPE90100225661@YESB...,0000924521218945,02/09/19,140,NaN,32.9
23,05/09/19,UPI-SOMIL SHARMA-SOMILSHARMA8@YBL-ORBC0105222-...,0000924818885710,05/09/19,NaN,1000,1032.9
24,05/09/19,UPI-UBER INDIA SYSTEMS P-UBER@AXISBANK-UTIB000...,0000924818889186,05/09/19,46,NaN,986.9
25,06/09/19,UPI-GOOGLEPAY-GOOG-PAYMENT@OKAXIS-UTIB0000553-...,0000924920030008,06/09/19,NaN,51,1037.9
26,09/09/19,UPI-ANUSHKA DRISHTI PANJ-ANUSHKAPANJABI97@OKIC...,0000925222681404,09/09/19,NaN,100,1137.9
27,10/09/19,UPI-TEA HALT EY GGN-PAYTM-8788094@PAYTM-PYTM...,0000925311109539,10/09/19,110,NaN,1027.9
28,10/09/19,UPI-ASHISH BANSAL-ASHISH.BANSAL8950@OKHDFCBANK...,0000925313733204,10/09/19,NaN,615,1642.9
29,12/09/19,UPI-TEA HALT EY GGN-PAYTM-8788094@PAYTM-PYTM...,0000925512779948,12/09/19,85,NaN,1557.9
...,...,...,...,...,...,...,...
106,20/10/19,UPI-MATA SHEETLA STATION-PAYTM-8745586@PAYTM-P...,0000929312614087,20/10/19,410,NaN,556.16
107,20/10/19,UPI-KRISHNA KHATANA-PAY9910260676@PAYTM-PYTM01...,0000929316714504,20/10/19,20,NaN,536.16
108,20/10/19,UPI-PANJABI CHAAP CORNER-Q71052680@YBL-UTIB000...,0000929316765190,20/10/19,100,NaN,436.16
109,21/10/19,NEFT CR-HSBC0560002-EY GLOBAL DELIVERY SERVICE...,HSBCN19294654738,21/10/19,NaN,4020.49,4456.65
110,23/10/19,UPI-ANUSHKA DRISHTI PANJ-ANUSHKAPANJABI97@OKIC...,0000092960951332,23/10/19,250,NaN,4206.65
111,24/10/19,UPI-ANUSHKA DRISHTI PANJ-ANUSHKAPANJABI97@OKIC...,0000929722190303,24/10/19,250,NaN,3956.65
112,25/10/19,UPI-ANUSHKA DRISHTI PANJ-ANUSHKAPANJABI97@OKIC...,0000092987996616,25/10/19,NaN,100,4056.65
113,25/10/19,UPI-ANUSHKA DRISHTI PANJ-ANUSHKAPANJABI97@OKIC...,0000092987999108,25/10/19,100,NaN,3956.65
114,25/10/19,NEFT CR-HSBC0560002-EY GLOBAL DELIVERY SERVICE...,HSBCN19298629799,25/10/19,NaN,529,4485.65
115,26/10/19,UPI-ANUSHKA DRISHTI PANJ-ANUSHKAPANJABI97@OKIC...,0000929919710048,26/10/19,NaN,101,4586.65
116,26/10/19,UPI-AVNESH KUMAR-AVINESHKUMAR842@OKAXIS-CORP00...,0000929920379718,26/10/19,351,NaN,4235.65
117,27/10/19,UPI-ANUSHKA DRISHTI PANJ-ANUSHKAPANJABI97@OKIC...,0000093008647375,27/10/19,201,NaN,4034.65
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,********,**********************************,************,********,******************,******************,******************
120,**********************************************...,NaN,NaN,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,STATEMENT SUMMARY :-,NaN,NaN,NaN,NaN,NaN,NaN
123,Opening Balance,NaN,NaN,NaN,Debits,Credits,Closing Bal
124,1382.9,NaN,NaN,NaN,62170.8,64822.6,4034.65
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,NaN,NaN,NaN,NaN,Dr Count,Cr Count,NaN
127,NaN,NaN,NaN,NaN,72,25,NaN
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,Generated On:,27-Oct-2019 08:56,Generated By:,111597639,Requesting Branch Code:,NET,NaN
131,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,State account branch GSTN:,19AAACH2702H1ZX,NaN,NaN,NaN,NaN,NaN
133,HDFC Bank GSTIN number details are available a...,NaN,NaN,NaN,NaN,NaN,NaN
134,"Registered Office Address: HDFC Bank House, Se...",NaN,NaN,NaN,NaN,NaN,NaN
135,--- End Of Statement ---,NaN,NaN,NaN,NaN,NaN,NaN