In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
pd.__version__

'0.24.2'

Modes in Jupyter Notebooks (states of codeblocks)

Markdown mode: Useful for everything outside of code, eg : for generating headers/comments, embedding videos, images and audio files

Command mode: operates on the top layer of the notebook, triggered by pressing the Esc key, allows us to use keyboard shortcuts, commands issued in command mode are not interpreted as commands

In [6]:
# Adding rows

In [13]:
# Generating Output

2 + 3

5

In [8]:
# Browsing Jupyter Shortuts using Esc+H

In [10]:
# Dataframe Output 

pd.read_csv('jamesbond.csv')

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [11]:
# Restart Kernel, whenever code is stuck in an infinite loop or cell blocks won't execute